server:
  port: 7000
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/staubjoao/sistemas_distribuidos_trabalho_3
          search-paths: config
