server:
  port: 8090
spring:
  datasource:
    url: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue:
      name: teste
